global:
  scrape_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - /etc/prometheus/rules/alerts.yml
  - /etc/prometheus/rules/alerts.dynamic.yml


scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: kafka-exporter
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse-exporter:9116']

  - job_name: 'spark'
    metrics_path: '/metrics/prometheus'
    static_configs:
      - targets: ['spark-master:8080', 'spark-worker:8081']

  - job_name: 'hdfs'
    static_configs:
      - targets: ['namenode:9981']
    metrics_path: '/metrics'